### ISSUE TITLE
Recursive types cannot be seen twice

### ISSUE THREAD

**Issue by DanielHoffmann-BO** [krzysztofreczek/go-structurizr#155]
If I have a type that reads as recursive, like a logger from the zap package, or a connection pool from pgx, it will only be seen as a child of a single type, even if it is in multiple parents. I have several types that have a logger, but only the first one shows a connection to `zap.Logger`, and I have multiple Store types that share the same `pgxpool.Pool`, but again, only the first one shows a connection in the graph.

**Comment by krzysztofreczek** [comment]
Hi @DanielHoffmann-BO, thank you for raising this issue. Let me try to recreate that and check if this can be fixed. 

I remember there is a piece of code that prevents the generation an infinite graph with a recursive loop. I need to revisit that.

**Comment by krzysztofreczek** [comment]
@DanielHoffmann-BO, can you pleas check if the latest version fixes the issue on your side?

**Comment by DanielHoffmann-BO** [comment]
Hey, just checked and it works! Thanks so much!
