### ISSUE TITLE
valid shapes?

### ISSUE THREAD

**Issue by pmeyerson** [krzysztofreczek/go-structurizr#98]
Thanks for this project!
Experimenting with documenting my own project.
Is there any info on what shapes are available?
I see I can use shape: database but haven't been able to find anything else that works yet.

**Comment by krzysztofreczek** [comment]
HI @pmeyerson , you're welcome.

Shapes should support all plantUML diagram elements. You can find them here: https://crashedmind.github.io/PlantUMLHitchhikersGuide/PlantUMLSpriteLibraries/plantuml_sprites.html#review-the-deployment-diagram-elements

Please let me know if it works for you.
